// hjudge.WebHost/src/Frontend/src/components/about/about.tsx
﻿import * as React from 'react';
import { Header, Icon, Item, Divider } from 'semantic-ui-react';
import { setTitle } from '../../utils/titleHelper';

const About = () => {
  const upgradeLogs = [{
    version: 'Beta: v1.7',
    date: '2018/11/28',
    content: [
      '1. 全部板块上线讨论功能',
      '2. 部分消息功能上线',
      '3. 性能优化',
      '4. 评测机改进',
      '5. 其他细节优化'
    ]
  },
  {
    version: 'Beta: v1.6',
    date: '2018/11/21',
    content: [
      '1. 优化 UI',
      '2. 改善用户体验',
      '3. 发送消息获得经验',
      '4. 添加每日登录奖励',
      '5. 编辑器支持 Markdown',
      '6. 性能优化',
      '7. 添加代码编辑器和语法高亮'
    ]
  },
  {
    version: 'Beta: v1.5',
    date: '2018/11/15',
    content: [
      '1. 添加版聊功能',
      '2. 重新设计关于界面',
      '3. 重新设计主页',
      '4. 开放重新评测权限'
    ]
  },
  {
    version: 'Stable: v1.4',
    date: '2018/10/21',
    content: [
      '1. 添加题目通过比率',
      '2. 添加菜单按钮提示',
      '3. 支持为单独题目设置语言限制'
    ]
  },
  {
    version: 'Stable: v1.3',
    date: '2018/10/20',
    content: [
      '1. 添加邮箱验证功能',
      '2. 优化用户体验，全部操作无需重新载入页面',
      '3. 添加 CSRF 攻击防御'
    ]
  },
  {
    version: 'Stable: v1.2',
    date: '2018/10/09',
    content: [
      '1. 添加密码重置功能'
    ]
  },
  {
    version: 'Stable: v1.1',
    date: '2018/10/08',
    content: [
      '1. 修复后退页面列表不会更新的 Bug',
      '2. 更换页面跳转实现方式',
      '3. 兼容 IE 11',
      '4. 评测逻辑 Bug 修复',
      '5. 其他优化'
    ]
  },
  {
    version: 'Stable: v1.0',
    date: '2018/10/05',
    content: [
      '1. 排名功能上线',
      '2. 添加小组和消息功能占位',
      '3. H:: Judge 正式版来啦'
    ]
  },
  {
    version: 'Beta: v0.4',
    date: '2018/10/04',
    content: [
      '1. 核心功能基本完成',
      '2. 添加夜间模式',
      '3. Bug 修复'
    ]
  },
  {
    version: 'Alpha: v0.3',
    date: '2018/10/03',
    content: [
      '1. 管理功能全部完成',
      '2. Bug 修复'
    ]
  },
  {
    version: 'Alpha: v0.2',
    date: '2018/10/02',
    content: [
      '1. 比赛功能上线',
      '2. 引入新的评测机',
      '3. Bug 修复'
    ]
  },
  {
    version: 'Alpha: v0.1',
    date: '2018/10/01',
    content: [
      '1. 船新的 H::Judge 建造出来啦~'
    ]
  }];

  setTitle('关于');

  return (
    <>
      <Header as='h1'>H::Judge</Header>
      <p>这是你从未上过的船新 H::Judge</p>
      <div>
        <Divider horizontal>
          <Header as='h4'>
            <Icon name='tag'></Icon> 更新日志
            </Header>
        </Divider>
        <Item.Group>
          {
            upgradeLogs.map((v, i) =>
              <React.Fragment key={i}>
                <Item>
                  <Item.Content>
                    <Item.Header>{v.version}</Item.Header>
                    <Item.Meta>{v.date}</Item.Meta>
                    <Item.Description>
                      {v.content.map((vc, ic) => <p key={ic}>{vc}</p>)}
                    </Item.Description>
                  </Item.Content>
                </Item>
                <Divider />
              </React.Fragment>
            )
          }
        </Item.Group>
      </div>
    </>
  );
}

export default About;

// hjudgeWeb/ClientApp/components/about/about.vue
﻿<template>
    <v-container>
        <v-card>
            <v-card-title primary-title>
                <p>
                    <h2>关于 H::Judge</h2>
                    <v-spacer></v-spacer>
                    这是你从来没有上过的船新 H::Judge，快来体验吧
                </p>
            </v-card-title>
            <v-card-text>
                <p>开发者：hez2010，Email：<a href="mailto:hez2010@126.com">hez2010@126.com</a></p>
                <v-container>
                    <h3>更新日志</h3>
                    <strong>2018/10/21 1.4 Stable</strong>
                    <small><strong>1.</strong> 添加题目通过比率</small>
                    <small><strong>2.</strong> 添加菜单按钮提示</small>
                    <small><strong>3.</strong> 支持为单独题目设置语言限制</small>
                    <br />
                    <strong>2018/10/20 1.3 Stable</strong>
                    <small><strong>1.</strong> 添加邮箱验证功能</small>
                    <small><strong>2.</strong> 优化用户体验，全部操作无需重新载入页面</small>
                    <small><strong>3.</strong> 添加 CSRF 攻击防御</small>
                    <br />
                    <strong>2018/10/9 1.2 Stable</strong>
                    <small><strong>1.</strong> 添加密码重置功能</small>
                    <br />
                    <strong>2018/10/8 1.1 Stable</strong>
                    <small><strong>1.</strong> 修复后退页面列表不会更新的 Bug</small>
                    <small><strong>2.</strong> 更换页面跳转实现方式</small>
                    <small><strong>3.</strong> 兼容 IE 11</small>
                    <small><strong>4.</strong> 评测逻辑 Bug 修复</small>
                    <small><strong>5.</strong> 其他优化</small>
                    <br />
                    <strong>2018/10/5 1.0 Stable</strong>
                    <small><strong>1.</strong> 排名功能上线</small>
                    <small><strong>2.</strong> 添加小组和消息功能占位</small>
                    <small><strong>3.</strong> H::Judge 正式版来啦</small>
                    <br />
                    <strong>2018/10/3 0.4 Beta</strong>
                    <small><strong>1.</strong> 核心功能基本完成</small>
                    <small><strong>2.</strong> 添加夜间模式</small>
                    <small><strong>3.</strong> Bug 修复</small>
                    <br />
                    <strong>2018/10/4 0.3 Alpha</strong>
                    <small><strong>1.</strong> 管理功能全部完成</small>
                    <small><strong>2.</strong> Bug 修复</small>
                    <br />
                    <strong>2018/10/2 0.2 Alpha</strong>
                    <small><strong>1.</strong> 比赛功能上线</small>
                    <small><strong>2.</strong> 引入新的评测机</small>
                    <small><strong>3.</strong> Bug 修复</small>
                    <br />
                    <strong>2018/10/1 0.1 Alpha</strong>
                    <small><strong>1.</strong> 船新的 H::Judge 建造出来啦~</small>
                </v-container>
            </v-card-text>
        </v-card>
    </v-container>
</template>

<script type="text/javascript" src="./about.js"></script>
